apiVersion: v1
kind: Service
metadata:
  name: mail
  labels:
    app.kubernetes.io/name: mail
    app.kubernetes.io/part-of: funnelmanager
spec:
  selector:
    app.kubernetes.io/name: mail
  ports:
    - name: http
      port: 8004
      targetPort: 8004
