apiVersion: v1
kind: Service
metadata:
  name: knowledge
  labels:
    app.kubernetes.io/name: knowledge
    app.kubernetes.io/part-of: funnelmanager
spec:
  selector:
    app.kubernetes.io/name: knowledge
  ports:
    - name: http
      port: 8007
      targetPort: 8007
