apiVersion: v1
kind: Service
metadata:
  name: agents
  labels:
    app.kubernetes.io/name: agents
    app.kubernetes.io/part-of: funnelmanager
spec:
  selector:
    app.kubernetes.io/name: agents
  ports:
    - name: http
      port: 8006
      targetPort: 8006
