apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: identity
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: funnelmanager
data:
  hostname: https://kc.x9bc433.win
